trigger:
- main

pool: default

steps:
 - task: TerraformInstaller@1
   inputs:
     terraformVersion: 'latest'
 - task: TerraformTaskV4@4
   inputs:
     provider: 'azurerm'
     command: 'custom'
     workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
     commandOptions: 'terraform fmt'
     outputTo: 'console'
     environmentServiceNameAzureRM: 'jio-it-Service-connection'

 - script: |
     terraform init
     terraform validation 
     terraform fmt
     terraform plan 
     terraform apply -auto-approve
   displayName: "run terraform Command"
